<a href="https://colab.research.google.com/github/ANJALICHAMOLI/PyTorch/blob/main/3_pytorch_traning_pipeline_real_world_dataset_manually.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 1.27801271,  0.66002323,  1.21691234, ...,  0.37668507,
         0.31114956, -0.42035223],
       [ 1.33007755,  1.41186867,  1.41047157, ...,  1.08836531,
         0.83635938,  0.76531108],
       [-0.29839514,  0.3945278 , -0.32693292, ..., -0.76048588,
         0.44754734, -1.0617677 ],
       ...,
       [-0.91738831,  0.55899399, -0.95810432, ..., -1.71586729,
        -0.70948206, -0.97606368],
       [-0.29839514,  0.63887757, -0.15904132, ...,  1.41006299,
         2.30067571,  1.27735168],
       [ 0.21068336, -1.02458048,  0.15107423, ...,  0.18245251,
         0.31114956, -0.1053763 ]])

In [ ]:
y_train

134    M
30     M
150    B
265    M
280    M
      ..
60     B
4      M
550    B
8      M
347    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
#using label encoder to convert y train data to nos
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

### Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[ 1.2780,  0.6600,  1.2169,  ...,  0.3767,  0.3111, -0.4204],
        [ 1.3301,  1.4119,  1.4105,  ...,  1.0884,  0.8364,  0.7653],
        [-0.2984,  0.3945, -0.3269,  ..., -0.7605,  0.4475, -1.0618],
        ...,
        [-0.9174,  0.5590, -0.9581,  ..., -1.7159, -0.7095, -0.9761],
        [-0.2984,  0.6389, -0.1590,  ...,  1.4101,  2.3007,  1.2774],
        [ 0.2107, -1.0246,  0.1511,  ...,  0.1825,  0.3111, -0.1054]],
       dtype=torch.float64)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
# defining the nn
class NN():

  def __init__(self, X): #X=traning set

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# create model
model = NN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # making gradients zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.5475454738938073
Epoch: 2, Loss: 3.422332154067853
Epoch: 3, Loss: 3.2942245994245307
Epoch: 4, Loss: 3.1594140899058756
Epoch: 5, Loss: 3.019008057917845
Epoch: 6, Loss: 2.874483144902174
Epoch: 7, Loss: 2.722582875086024
Epoch: 8, Loss: 2.5713435942269136
Epoch: 9, Loss: 2.415496571546269
Epoch: 10, Loss: 2.2523132708121176
Epoch: 11, Loss: 2.0885786604487615
Epoch: 12, Loss: 1.9267189160157674
Epoch: 13, Loss: 1.7688980818011228
Epoch: 14, Loss: 1.6166813558405826
Epoch: 15, Loss: 1.4720089857075795
Epoch: 16, Loss: 1.3395536084356316
Epoch: 17, Loss: 1.2188435529093358
Epoch: 18, Loss: 1.1152359743513593
Epoch: 19, Loss: 1.0299181889995548
Epoch: 20, Loss: 0.9629659688367034
Epoch: 21, Loss: 0.9127293042028659
Epoch: 22, Loss: 0.8759998180156439
Epoch: 23, Loss: 0.8492250536106901
Epoch: 24, Loss: 0.8294192408174715
Epoch: 25, Loss: 0.8143822448440734

In [ ]:
model.weights

tensor([[ 0.3342],
        [ 0.1400],
        [ 0.2606],
        [-0.1355],
        [-0.0744],
        [ 0.2407],
        [ 0.2409],
        [ 0.1032],
        [ 0.1172],
        [ 0.4398],
        [-0.0886],
        [ 0.8213],
        [ 0.2490],
        [-0.2614],
        [ 0.4311],
        [ 0.0870],
        [-0.0316],
        [ 0.2711],
        [ 0.1903],
        [ 0.2395],
        [ 0.3818],
        [ 0.1194],
        [ 0.2273],
        [ 0.1727],
        [ 0.4061],
        [-0.3270],
        [-0.1425],
        [-0.1078],
        [ 0.1188],
        [ 0.2356]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.0126], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6862111687660217